name: Makefile CI

on:
  push:
    branches: [ "richelieu" ]
  pull_request:
    branches: [ "richelieu" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: panchajanya1999/archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup env
        run: pacman -Syu --needed --noconfirm wget base-devel xmlto inetutils bc cpio python-sphinx python-sphinx_rtd_theme graphviz imagemagick git python zip github-cli fortune-mod ccache
      - name: Initialize ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 2048M
      - name: Build  Kernel
        run: |
          bash build_script.sh
        env:
          token: ${{ secrets.TG_TOKEN }}

   
    
      - name: LS
        run: ls

      - name: Store Kernel Package as Artifact
        uses: actions/upload-artifact@v4
        with:
         name: Flashable zip
         path: AnyKernel3/package.zip


