name: Makefile CI

on:
  push:
    branches: [ "richelieu" ]
  pull_request:
    branches: [ "richelieu" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Initialize ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
          max-size: 2048M

    - name: update
      run: sudo apt-get update
    - name: Install package
      run: sudo apt install build-essential clang gcc ccache git wget base-devel xmlto inetutils bc cpio python-sphinx python-sphinx_rtd_theme graphviz imagemagick git python zip github-cli fortune-mod ccache

    - name: Install package2
      run: sudo apt-get install git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

    - name: Build
      run: sudo bash build_script.sh

    
    - name: LS
      run: ls


